language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: 46.0
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install -g bower
- bower install
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s "default"; fi
