language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester
- bower install
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: vh8PhKo4w9kGiwgfy0eN/j4aaqRm8VyLHFTRTHxNFOn3wGmLyffc8V4e/i/2iLG/NsnugNPUgxq/iHcpNCuPfXq/SRpbm34XzyXoihD1b7QFktB0SItX2gKfdhpctiJKQPvmJTaATDpu+eJHXTtZVbV/4hpbQfipDZ4MPNvcvPq15OHZpvGpBWRWmDJb1nrlnhUAzFmS8k9ytKHiZBri5ztEk++stuj4my6JOO23ccbvGVndmKGtNTSTq3R9Ndw+ULygQhujHYI+bWDExhA38wdpQVWDJY80aLHvAftRuhreQt5/hK/krk2nU5suB4q1bf7kEvCrNKGmyN5dj3NTPxLz0K4+57drSCPN9sPPwMS5CTsAT5sWKabTK0qYE2CqBYtq4NcIVSVji5WD+0yTbShFFgCSLa7jdF2sQ1WbNEQUjRHI75S5jOWi3BJJxENupnxnlkq60ttJT05EL9bf0iMqnSrK8WnITxR0sihwWkx2tMCJGEtyXe90XUK5X3hFjRSgn3jP+/RhlwUDA8+hVecn7XISLo70TsE8p/txApzgh5w/B0YTKFziIBbPqUdPsaZYVKuUjrKkNSBbYS0HBR1yvZNRsOu1Leeb4BgDwhOqi2oNZW01xHJo0E+xNGDkXXWfXozAKnWGC93DrEbUyobHHR6kYRPRk3E5fMBt23A=
  - secure: cShlo6jEv/yxlTit70topW0p8w96G74jGOa7t6Vs5BJ7C/5nppReQhynlk5ozDgdugcyRfIKyPBAHlnbjVAhhwWzgovsjwK+ESOuhx9Lci+WBf6rls9JCC0YxwzPXEeKpVQ3rbMSKsDNo4Z6olYwugxcCzeAJYUFejE3phAy7ac46xqc7sB2zF6iDMYdVCejV3FHOgpHWUI8PWzr8P9M3oP7AhcvqGh3DyNrgH+qz4wXGGGikDCbJE1jNjFZO9Z+CvcOSEnlEl2XyzhC+yjE1Lwz29cAWWsZ6pQH18oxTtb2rOf1ioRE01R0v7nTP9pN/tDWCUZq6wnIS+kWe2Zd7X6RDTmnOYyElR5g43Imw8S03smfOf1wj83UiDqkDhkT1sStBzlTMEhl+jdug0D5QxK2z90CfSCn0MJuvLRa0dCQTp84lrWUgbVxIEMhA01wqa7PdROOi4RvRbkCGq18VgoekYLyt3InXBMtgGjM6miv4chD8GnbdixUSZZBLmu/VoKVZJQyHZ1a39DrKjta8QVPh8hH6cgXFttWSeJv1TrhFoKWRFkC/fdls4WxVhO+6mVbG41MXObZ+mj+7S8/qxvDMI3CPSoz8ak1T+ksv+vSWf4OskXPhoMTmdP3gWyrf8vjqLon1FR69azRtx0hmsMGkIaE2xV/0iRhPPAHfb8=
